version: "3"
services:
  angular:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - angular_node_modules:/angular-18/node_modules
      - ../:/angular-18
    command: sh -c "npm install & sleep infinity"
    networks:
      - devcontainer-network
    ports:
      - "4200:4200"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 2G
      
  firebase-emulators:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile.emulators
    volumes:
      - ../firebase:/firebase-emulators
      - firebase_node_modules:/firebase-emulators/node_modules
      - ../package.json:/firebase-emulators/package.json
      - ../package-lock.json:/firebase-emulators/package-lock.json
    ports:
      - "4000:4000"
      - "5001:5001"
      - "8080:8080"
    # command: firebase emulators:start
    command: sh -c "npm install && firebase emulators:start"
    networks:
      - devcontainer-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '2'
          memory: 500M


volumes:
  angular_node_modules:
  firebase_node_modules:
networks:
  devcontainer-network:
    driver: bridge