# Use Node.js base image
FROM node:22-alpine

# Set the working directory
WORKDIR /firebase-emulators

# Install Java 11
RUN apk add openjdk11-jre


# Install Firebase CLI
RUN npm install -g firebase-tools

# Expose required ports
EXPOSE 4000 5001 8080